### PR TITLE
Added extender directory

### PR DESCRIPTION
**Pull request by psiinon**

### CODE REVIEW

**Comment by kingthorin** [comment]
Here too?
https://github.com/zaproxy/zaproxy/tree/develop/src/scripts/templates

**Comment by psiinon** [comment]
I was actually thinking we should move these from the core into the scripts add-on - that way we can patch them without re-releasing the core.
wdyt?
In any case, the core doesnt actually know about extender scripts, they are just defined in the scripts addon.

**Comment by kingthorin** [comment]
Moving them sounds good to me.

**Comment by thc202** [comment]
I'm fine with the move as well.

**Comment by thc202** [comment]
We could also move the script extension into an add-on, not just its templates.

**Pull request merged**
