### PR TITLE
Replace deprecated code in targeted script

### PR DESCRIPTION
**Pull request by thc202**
Use the requester add-on to display the message in the editor dialogue.

Needs zaproxy/zap-extensions#5542.

### CODE REVIEW

**Comment by psiinon** [comment]
Will also need the requester add-on to be released once that PR has been merged?

**Comment by thc202** [comment]
Does not need to be done now but we should release the requester add-on before releasing this one.

**Comment by psiinon** [comment]
People might use these as examples on their own, without using the add-on.
If they do that before the requester is released then this script will fail.

**Comment by thc202** [comment]
This can wait for the release then.

**Comment by kingthorin** [comment]
Changes look good to me

**Review by kingthorin — APPROVED** [review]

**Review by psiinon — APPROVED** [review]

**Pull request merged**
