### PR TITLE
Add new script for changing user-agents while fuzzing.

### PR DESCRIPTION
**Pull request by be1807v**
Hi! I made a small script that changes your user-agent while fuzzing. This can sometimes help bypassing rate-limiting while fuzzing! I found that this was usefull so I want to share it with the others!
Thank you!

### CODE REVIEW

**Comment by thc202** [comment]
You'll have to setup the name and email:
https://docs.github.com/en/github/using-git/setting-your-username-in-git
https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address

**Comment by be1807v** [comment]
@thc202 Hi, I just did it, email was already configured. Thanks!

**Comment by thc202** [comment]
You need to amend the commit and push to update with the new values then.

**Comment by kingthorin** [comment]
Something like `git commit —amend —no-edit —reset-author —signoff` then `git push —force`

**Comment by be1807v** [comment]
@kingthorin , thanks was looking for to command. I will do this tomorrow (2am here).

**Comment by kingthorin** [comment]
If you're having trouble we can help out.  Just hop into [IRC](https://zaproxy.org/irc) and let us know.

**Comment by be1807v** [comment]
@kingthorin Thank you, I just joined the chat

**Comment by thc202** [comment]
Thanks!

**Pull request merged**
