### PR TITLE
Spoof IP (X-Forwarded-For) randomly each req.

### PR DESCRIPTION
**Pull request by ChristSent**

### CODE REVIEW

**Comment by kingthorin** [comment]
Is there a reason this is being added in the root instead of the applicable folder?

**Comment by ChristSent** [comment]
Yea, my mistake. I intended to add this to the httpfuzzerprocessor folder.

**Comment by kingthorin** [comment]
No worries, I'll tweak the PR.

**Comment by thc202** [comment]
And update the changelog? :)

**Comment by kingthorin** [comment]
Sure, done.

**Comment by thc202** [comment]
Thank you (both)!

**Pull request merged**
