### PR TITLE
Lots of regex-based search scripts

### PR DESCRIPTION
**Pull request by kurobeats**
A collection of regex-based search scripts. Most will be penetration test/pipeline scan specific, users won't want to enable them all.

### CODE REVIEW

**Comment by psiinon** [comment]
Thanks for these!
Sorry, but we decided on a new naming standard recently, as per https://twitter.com/psiinon/status/1504475442484432897 so could you rename your scripts to use CamelCase?
We should document that in this repo ;)

**Comment by psiinon** [comment]
Also, have you noticed the build failure?
```
VerifyScripts > shouldParseScript(Consumer, String, Path) > org.zaproxy.VerifyScripts.shouldParseScript(Consumer, String, Path)[42] FAILED
    java.lang.RuntimeException at VerifyScripts.java:162
        Caused by: javax.script.ScriptException at VerifyScripts.java:160
            Caused by: jdk.nashorn.internal.runtime.ParserException at VerifyScripts.java:160
```

**Comment by kurobeats** [comment]
> Also, have you noticed the build failure?
> 
> ```
> VerifyScripts > shouldParseScript(Consumer, String, Path) > org.zaproxy.VerifyScripts.shouldParseScript(Consumer, String, Path)[42] FAILED
>     java.lang.RuntimeException at VerifyScripts.java:162
>         Caused by: javax.script.ScriptException at VerifyScripts.java:160
>             Caused by: jdk.nashorn.internal.runtime.ParserException at VerifyScripts.java:160
> ```

Interesting. I'll have a dig.

**Comment by kurobeats** [comment]
OK, should be good. Mostly. I missed a few sign offs initially, I hope its not a problem.

**Comment by kingthorin** [comment]
Think you can address that latest LGTM finding?

**Comment by kurobeats** [comment]
Sorry mate! The infamous global virus got me then I lost sight of it...I'll definitely look to remediate when I get some air

**Comment by kingthorin** [comment]
No problem. Take care of yourself!

**Comment by kingthorin** [comment]
@kurobeats have you recovered, are you able to look at finishing this?

**Comment by thc202** [comment]
lgtm is indeed dead, this would have to be rebased to pick the latest checks.

**Pull request closed without merging**
