### PR TITLE
Add scripts about CSP policies notification feature and SameSite cookie protection

### PR DESCRIPTION
**Pull request by righettod**
See #37 sorry...

### CODE REVIEW

**Comment by thc202** [comment]
Looks good to me, thank you!

**Comment by righettod** [comment]
Thanks you very much to both of you for your supports  :+1:

**Comment by righettod** [comment]
Small question: Does any existing Zap instance with the "community scripts" plugin installed will receive the update ?

**Comment by kingthorin** [comment]
No unfortunately the current "Community Scripts" plugin is statically packaged. 
The future plan is (as far as I know) to Dynamically gather the scripts.

**Comment by righettod** [comment]
OK thanks you.
I think that, at packaging time, the build take a clone of the repository no ?

**Comment by kingthorin** [comment]
Looking at: https://github.com/zaproxy/zap-extensions/tree/alpha/src/org/zaproxy/zap/extension/communityScripts they're all statically included. So updating requires that files/community-scripts entries are updated (added/removed/updated), then the package rebuilt.

**Comment by thc202** [comment]
A new version of the add-on will be released soon (probably at the same time, or shortly after, the release of ZAP 2.5.0).

**Comment by righettod** [comment]
OK thanks you very much for the answer :+1:

**Pull request merged**
