### PR TITLE
HUNT.py: refactor, improve perf & readability, fix bugs

### PR DESCRIPTION
**Pull request by nil0x42**
## Commit list (most recent first)

commit 952be4c0896d8f482a5693498e07e2e340fdc8b4

    HUNT.py: add '(HUNT script)' as alert title suffix
---
commit 4b992ef7d58fb6a99c2d8f273bed2ca8c1ae9fee

    HUNT.py: factorize alert, improve code readability
    
    - factorize alert creation into `hunt_alert()` function
    - make alert descriptions more readable
---
commit 09b9e4620399ac940911c1edf3bd6aa11143f0e3

    HUNT.py: add function for redundant match code
    
    * The `result` matches where always the same, so separated it
      into a separate function.
    * As `re.match('.*X', string)` is equal to `X in string`, stop
      using regex in `find_words_in_params()` to improve readability.
---
commit 7741e05f93ab513b02b67a8275f5ff368f846f93

    HUNT.py: refactor code
    
    * remove unneeder cast to str()
    * remove unneeded `globalvar` initialization
    * rename `regex` var (which is not a regex)
    * limit unneeded nesting
---
commit ab5e6d6ab6f228dda9564bed915ba0e9cf31b229

    HUNT.py: perf: leave script if not params
---
commit 247cc0ae2e252a1a4b3c8f3586f85602e8ebf2f8

    HUNT.py: refactor: limit unneeded nesting
---
commit a138a0d40e255626e09d52c7e1e943cda3b45833

    HUNT.py: improve base_uri regex performance
    
    previous regex had useless capturing groups
    and didn't ensure that match is found at start of string ('^')
---
commit 87551dcaa351e275bd9940c869b2860656b44cce

    HUNT.py: fix appliesToHistoryType() condition
    
    previous condition was `histType <= 2`, which also includes
    TYPE_TEMPORARY.
    
    NOTE: new condition written in order to be easy to understand.

### CODE REVIEW

**Comment by thc202** [comment]
@sbzo PTAL.

**Comment by sbzo** [comment]
@thc202 I will use it for some days. I give you my feedback later.

Best regards,

RLobo.

**Comment by sbzo** [comment]
> @sbzo please take a look.

@thc202 every looks clear and everything is working as expected. Thanks, @nil0x42 for your contribution.

Best regards,

RLobo.

**Comment by kingthorin** [comment]
Squash?

**Comment by thc202** [comment]
Fine with merge commit (easier to read).

**Pull request merged**
