### PR TITLE
Added AF API example

### PR DESCRIPTION
**Pull request by psiinon**

### CODE REVIEW

**Comment by psiinon** [comment]
Will look at configuring the rules and scripts as per the packaged API scan...

**Review by kingthorin — APPROVED** [review]

**Comment by psiinon** [comment]
Updated to include the scripts and define the ascan rules the API packaged scan currently uses.
But WIP pending a review of those rules 😁

**Comment by psiinon** [comment]
Updated to match https://github.com/zaproxy/zaproxy/pull/8617

**Comment by psiinon** [comment]
No longer WIP :)

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Comment by psiinon** [comment]
Do you want to check this again @kingthorin ?

**Review by kingthorin — APPROVED** [review]

**Pull request merged**
