### PR TITLE
Score Security Maze script

### PR DESCRIPTION
**Pull request by psiinon**
Name in CamelCase as thats whats currently winning on https://twitter.com/psiinon/status/1504475442484432897 ;)

<details>
<summary>Example output (just std spider):</summary>

```
Security Crawl Maze Results

/test/css/font-face.found
				FAIL
/test/headers/content-location.found
				Standard
/test/headers/link.found
				Standard
/test/headers/location.found
				FAIL
/test/headers/refresh.found
				Standard
/test/html/doctype.found
				Standard
/test/html/manifest.found
				Standard
/test/html/body/background.found
				Standard
/test/html/body/a/href.found
				Standard
/test/html/body/a/ping.found
				Standard
/test/html/body/audio/src.found
				FAIL
/test/html/body/applet/archive.found
				FAIL
/test/html/body/applet/codebase.found
				FAIL
/test/html/body/blockquote/cite.found
				FAIL
/test/html/body/embed/src.found
				FAIL
/test/html/body/form/action-get.found
				Standard
/test/html/body/form/action-post.found
				FAIL
/test/html/body/form/button/formaction.found
				FAIL
/test/html/body/frameset/frame/src.found
				FAIL
/test/html/body/iframe/src.found
				Standard
/test/html/body/iframe/srcdoc.found
				Standard
/test/html/body/img/dynsrc.found
				FAIL
/test/html/body/img/lowsrc.found
				FAIL
/test/html/body/img/longdesc.found
				FAIL
/test/html/body/img/src-data.found
				FAIL
/test/html/body/img/src.found
				Standard
/test/html/body/img/srcset1x.found
				FAIL
/test/html/body/img/srcset2x.found
				FAIL
/test/html/body/input/src.found
				FAIL
/test/html/body/isindex/action.found
				FAIL
/test/html/body/map/area/ping.found
				FAIL
/test/html/body/object/data.found
				FAIL
/test/html/body/object/codebase.found
				FAIL
/test/html/body/object/param/value.found
				FAIL
/test/html/body/script/src.found
				Standard
/test/html/body/svg/image/xlink.found
				FAIL
/test/html/body/svg/script/xlink.found
				FAIL
/test/html/body/table/background.found
				FAIL
/test/html/body/table/td/background.found
				FAIL
/test/html/body/video/src.found
				FAIL
/test/html/body/video/poster.found
				FAIL
/test/html/head/profile.found
				FAIL
/test/html/head/base/href.found
				FAIL
/test/html/head/comment-conditional.found
				Standard
/test/html/head/import/implementation.found
				FAIL
/test/html/head/link/href.found
				Standard
/test/html/head/meta/content-csp.found
				FAIL
/test/html/head/meta/content-pinned-websites.found
				FAIL
/test/html/head/meta/content-reading-view.found
				Standard
/test/html/head/meta/content-redirect.found
				Standard
/test/html/misc/url/full-url.found
				FAIL
/test/html/misc/url/path-relative-url.found
				FAIL
/test/html/misc/url/protocol-relative-url.found
				Standard
/test/html/misc/url/root-relative-url.found
				Standard
/test/html/misc/string/dot-dot-slash-prefix.found
				FAIL
/test/html/misc/string/dot-slash-prefix.found
				FAIL
/test/html/misc/string/url-string.found
				FAIL
/test/html/misc/string/string-known-extension.pdf
				FAIL
/test/javascript/misc/comment.found
				FAIL
/test/javascript/misc/string-variable.found
				FAIL
/test/javascript/misc/string-concat-variable.found
				FAIL
/test/javascript/frameworks/angular/event-handler.found
				FAIL
/test/javascript/frameworks/angular/router-outlet.found
				FAIL
/test/javascript/frameworks/angularjs/ng-href.found
				FAIL
/test/javascript/frameworks/polymer/event-handler.found
				FAIL
/test/javascript/frameworks/polymer/polymer-router.found
				FAIL
/test/javascript/frameworks/react/route-path.found
				FAIL
/test/javascript/frameworks/react/index.html/search.found
				FAIL
/test/misc/known-files/robots.txt.found
				Standard
/test/misc/known-files/sitemap.xml.found
				FAIL
Tests:	70
Passes:	20
Fails:	50
Score:	29%

```

</details>

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

### CODE REVIEW

**Comment by psiinon** [comment]
Theres a bug in this code .. will fix asap...

**Comment by psiinon** [comment]
Rewrote the script to make it work better - it can now show both Standard and Ajax results (previously it just showed one of the ones which worked, not both if they dod).
Output now looks like:

```
Security crawl Maze Results
---------------------------
/css/font-face.found
				FAIL	FAIL
/headers/content-location.found
				Pass	FAIL
/headers/link.found
				Pass	FAIL
/headers/location.found
				FAIL	Pass
/headers/refresh.found
				Pass	FAIL
/html/doctype.found
				Pass	FAIL
/html/manifest.found
				Pass	FAIL
/html/body/background.found
				Pass	Pass
/html/body/a/href.found
				Pass	FAIL
/html/body/a/ping.found
				Pass	FAIL
/html/body/audio/src.found
				FAIL	Pass
/html/body/applet/archive.found
				FAIL	FAIL
/html/body/applet/codebase.found
				FAIL	FAIL
/html/body/blockquote/cite.found
				FAIL	FAIL
/html/body/embed/src.found
				FAIL	Pass
/html/body/form/action-get.found
				FAIL	FAIL
/html/body/form/action-post.found
				FAIL	FAIL
/html/body/form/button/formaction.found
				FAIL	Pass
/html/body/frameset/frame/src.found
				FAIL	Pass
/html/body/iframe/src.found
				Pass	Pass
/html/body/iframe/srcdoc.found
				Pass	Pass
/html/body/img/dynsrc.found
				FAIL	FAIL
/html/body/img/lowsrc.found
				FAIL	FAIL
/html/body/img/longdesc.found
				FAIL	FAIL
/html/body/img/src-data.found
				FAIL	FAIL
/html/body/img/src.found
				Pass	Pass
/html/body/img/srcset1x.found
				FAIL	Pass
/html/body/img/srcset2x.found
				FAIL	FAIL
/html/body/input/src.found
				FAIL	Pass
/html/body/isindex/action.found
				FAIL	FAIL
/html/body/map/area/ping.found
				FAIL	FAIL
/html/body/object/data.found
				FAIL	Pass
/html/body/object/codebase.found
				FAIL	FAIL
/html/body/object/param/value.found
				FAIL	FAIL
/html/body/script/src.found
				Pass	Pass
/html/body/svg/image/xlink.found
				FAIL	Pass
/html/body/svg/script/xlink.found
				FAIL	Pass
/html/body/table/background.found
				FAIL	Pass
/html/body/table/td/background.found
				FAIL	Pass
/html/body/video/src.found
				FAIL	Pass
/html/body/video/poster.found
				FAIL	Pass
/html/head/profile.found
				FAIL	Pass
/html/head/base/href.found
				FAIL	FAIL
/html/head/comment-conditional.found
				Pass	FAIL
/html/head/import/implementation.found
				FAIL	FAIL
/html/head/link/href.found
				Pass	Pass
/html/head/meta/content-csp.found
				FAIL	FAIL
/html/head/meta/content-pinned-websites.found
				FAIL	FAIL
/html/head/meta/content-reading-view.found
				Pass	FAIL
/html/head/meta/content-redirect.found
				Pass	FAIL
/html/misc/url/full-url.found
				FAIL	FAIL
/html/misc/url/path-relative-url.found
				FAIL	FAIL
/html/misc/url/protocol-relative-url.found
				Pass	FAIL
/html/misc/url/root-relative-url.found
				Pass	FAIL
/html/misc/string/dot-dot-slash-prefix.found
				FAIL	FAIL
/html/misc/string/dot-slash-prefix.found
				FAIL	FAIL
/html/misc/string/url-string.found
				FAIL	FAIL
/html/misc/string/string-known-extension.pdf
				FAIL	FAIL
/javascript/misc/comment.found
				FAIL	FAIL
/javascript/misc/string-variable.found
				FAIL	FAIL
/javascript/misc/string-concat-variable.found
				FAIL	FAIL
/javascript/frameworks/angular/event-handler.found
				FAIL	FAIL
/javascript/frameworks/angular/router-outlet.found
				FAIL	FAIL
/javascript/frameworks/angularjs/ng-href.found
				FAIL	FAIL
/javascript/frameworks/polymer/event-handler.found
				FAIL	FAIL
/javascript/frameworks/polymer/polymer-router.found
				FAIL	FAIL
/javascript/frameworks/react/route-path.found
				FAIL	FAIL
/javascript/frameworks/react/index.html/search.found
				FAIL	FAIL
/misc/known-files/robots.txt.found
				Pass	FAIL
/misc/known-files/sitemap.xml.found
				FAIL	FAIL
Tests:	70
Passes:	34
Fails:	36
Score:	49%
```

Not sure which its not 50% as per https://www.zaproxy.org/docs/scans/crawlmaze/ but that is unlikely to be a problem with this script ;) Will look into that when I get a chance...

**Review by kingthorin — APPROVED** [review]

**Comment by kingthorin** [comment]
Did you purposefully use full caps for fail but title caps for pass?

**Comment by psiinon** [comment]
Yes :)

**Comment by kingthorin** [comment]
Okay, just wanted to be sure. On one hand I get wanting to make it stand out, on the other is my wanting consistency :wink:

**Comment by psiinon** [comment]
Pushed some changes but more incoming - @thc202 has pointed out that we need to check the http URLs as well...

**Comment by psiinon** [comment]
Updated to handle http URLs and show the scheme. Scores better too :D
New output:

```
Security crawl Maze Results			Scheme	Standard	Ajax
----				---	---
/css/font-face.found
				https	Pass	FAIL
/headers/content-location.found
				https	Pass	FAIL
/headers/link.found
				https	Pass	FAIL
/headers/location.found
				https	Pass	Pass
/headers/refresh.found
				https	Pass	FAIL
/html/doctype.found
				https	Pass	FAIL
/html/manifest.found
				https	Pass	FAIL
/html/body/background.found
				https	Pass	Pass
/html/body/a/href.found
				https	Pass	FAIL
/html/body/a/ping.found
				https	Pass	FAIL
/html/body/audio/src.found
				https	FAIL	Pass
/html/body/applet/archive.found
					FAIL	FAIL
/html/body/applet/codebase.found
					FAIL	FAIL
/html/body/blockquote/cite.found
					FAIL	FAIL
/html/body/embed/src.found
				https	FAIL	Pass
/html/body/form/action-get.found
					FAIL	FAIL
/html/body/form/action-post.found
				https	Pass	FAIL
/html/body/form/button/formaction.found
				https	FAIL	Pass
/html/body/frameset/frame/src.found
				https	Pass	Pass
/html/body/iframe/src.found
				https	Pass	Pass
/html/body/iframe/srcdoc.found
				https	Pass	Pass
/html/body/img/dynsrc.found
					FAIL	FAIL
/html/body/img/lowsrc.found
					FAIL	FAIL
/html/body/img/longdesc.found
				https	Pass	FAIL
/html/body/img/src-data.found
					FAIL	FAIL
/html/body/img/src.found
				https	Pass	Pass
/html/body/img/srcset1x.found
				https	FAIL	Pass
/html/body/img/srcset2x.found
					FAIL	FAIL
/html/body/input/src.found
				https	FAIL	Pass
/html/body/isindex/action.found
					FAIL	FAIL
/html/body/map/area/ping.found
				https	Pass	FAIL
/html/body/object/data.found
				https	FAIL	Pass
/html/body/object/codebase.found
					FAIL	FAIL
/html/body/object/param/value.found
					FAIL	FAIL
/html/body/script/src.found
				https	Pass	Pass
/html/body/svg/image/xlink.found
				https	FAIL	Pass
/html/body/svg/script/xlink.found
				https	FAIL	Pass
/html/body/table/background.found
				https	FAIL	Pass
/html/body/table/td/background.found
				https	FAIL	Pass
/html/body/video/src.found
				https	FAIL	Pass
/html/body/video/poster.found
				https	FAIL	Pass
/html/head/profile.found
				https	FAIL	Pass
/html/head/base/href.found
					FAIL	FAIL
/html/head/comment-conditional.found
				https	Pass	FAIL
/html/head/import/implementation.found
					FAIL	FAIL
/html/head/link/href.found
				https	Pass	Pass
/html/head/meta/content-csp.found
					FAIL	FAIL
/html/head/meta/content-pinned-websites.found
					FAIL	FAIL
/html/head/meta/content-reading-view.found
				https	Pass	FAIL
/html/head/meta/content-redirect.found
				https	Pass	FAIL
/html/misc/url/full-url.found
				https	Pass	FAIL
/html/misc/url/path-relative-url.found
				https	Pass	FAIL
/html/misc/url/protocol-relative-url.found
				https	Pass	FAIL
/html/misc/url/root-relative-url.found
				https	Pass	FAIL
/html/misc/string/dot-dot-slash-prefix.found
					FAIL	FAIL
/html/misc/string/dot-slash-prefix.found
					FAIL	FAIL
/html/misc/string/url-string.found
					FAIL	FAIL
/html/misc/string/string-known-extension.pdf
					FAIL	FAIL
/javascript/misc/comment.found
				https	Pass	FAIL
/javascript/misc/string-variable.found
				https	Pass	FAIL
/javascript/misc/string-concat-variable.found
					FAIL	FAIL
/javascript/frameworks/angular/event-handler.found
					FAIL	FAIL
/javascript/frameworks/angular/router-outlet.found
					FAIL	FAIL
/javascript/frameworks/angularjs/ng-href.found
					FAIL	FAIL
/javascript/frameworks/polymer/event-handler.found
					FAIL	FAIL
/javascript/frameworks/polymer/polymer-router.found
					FAIL	FAIL
/javascript/frameworks/react/route-path.found
					FAIL	FAIL
/javascript/frameworks/react/index.html/search.found
					FAIL	FAIL
/misc/known-files/robots.txt.found
				https	Pass	FAIL
/misc/known-files/sitemap.xml.found
				https	Pass	FAIL
Tests:	70
Passes:	43
Fails:	27
Score:	61%
```

**Review by kingthorin — APPROVED** [review]

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Pull request merged**
