### PR TITLE
Update js scripts to use passed variables

### PR DESCRIPTION
**Pull request by ricekot**

### CODE REVIEW

**Review by thc202 — APPROVED** [review]

**Comment by thc202** [comment]
Thank you!

**Comment by kingthorin** [comment]
As discussed earlier do other script languages need similar handling and could/should we be handilng at the add-on or engine vs in each script?

**Comment by thc202** [comment]
This handling is temporary, once 2.12 is out the checks will no longer be needed.

**Comment by kingthorin** [comment]
Perfect, thanks.

**Pull request merged**
