### PR TITLE
Normalise line endings in latest script

### PR DESCRIPTION
**Pull request by thc202**
Normalise line endings in aws-signing-for-owasp-zap.py, so they are
converted to the expected line endings on checkout.

### CODE REVIEW

**Comment by kingthorin** [comment]
> This pull request can't be analyzed because the commit could not be fetched from the repository

LGTM integration issue? Or, something related to the github issues the other day?

**Comment by thc202** [comment]
Probably the former, Travis CI was able to fetch the commits.

**Comment by rneatherway** [comment]
> LGTM integration issue? Or, something related to the github issues the other day?

Hi, I work on LGTM and just wanted to let you know we spotted this error and have investigated it. The cause is the unclean checkout, exactly the thing that this PR was opened to fix! As a result, when we create a synthetic merge commit to analyze, the `git merge` operation fails, as you can see in the [logs](https://lgtm.com/projects/g/zaproxy/community-scripts/logs/rev/pr-31ed4acf7626f78d6d3e5b27363caa9d21a1c233/lang:javascript/stage:Preparing%20merge%20commit) on LGTM. We're looking into how we can avoid this happening in the future. The good news is that issue won't affect your repository from now on.

**Comment by psiinon** [comment]
Hiya @rneatherway - thanks for the update! And I'm impressed with your diligence :)

**Comment by rneatherway** [comment]
:-)

**Pull request merged**
